before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
brews:
  - tap:
      owner: bestras-test-org
      name: go-cli-brews
    folder: Formula
    homepage: https://github.com/bestras-test-org/go-cli
    description: A fun TUI in go
    test: |
      system "#{bin}/go-cli"
