# This is a basic workflow that is manually triggered

name: Recategorize labeled discussions

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      label:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Label for discussions that will be recategorized'
        # Default value if no value is explicitly provided
        default: 'bug'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      category:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The name of the category the labeled discussions will be moved to'
        # Default value if no value is explicitly provided
        default: 'Ideas'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Moving Discussions labeled ${{ inputs.label }} to category ${{  inputs.category }}"
